import {
    Award,
    Bell,
    BookOpen,
    Briefcase,
    Building,
    Building2,
    Calendar,
    CheckCircle2,
    Clock,
    Code,
    Coins,
    CreditCard,
    Database,
    ExternalLink,
    Eye,
    Feather,
    Gauge,
    Globe,
    GraduationCap,
    Layers,
    Layout,
    LayoutDashboard,
    Lightbulb,
    Mail,
    MapPin,
    MessageCircle,
    Monitor,
    Moon,
    MoreHorizontal,
    Network,
    Palette,
    Plug,
    Puzzle,
    Rocket,
    Search,
    Server,
    Settings,
    ShieldCheck,
    ShoppingCart,
    Smartphone,
    Sparkles,
    Target,
    TrendingUp,
    Truck,
    Users,
    Wrench,
    Zap,
    NotebookPen,
} from 'lucide-react'

import { FaGithub, FaLinkedin  } from "react-icons/fa";


export const DYNAMIC_ICON_MAP = {
    award: Award,
    bell: Bell,
    bookOpen: BookOpen,
    briefcase: Briefcase,
    building: Building,
    building2: Building2,
    calendar: Calendar,
    checkCircle: CheckCircle2,
    clock: Clock,
    code: Code,
    coins: Coins,
    creditCard: CreditCard,
    database: Database,
    externalLink: ExternalLink,
    eye: Eye,
    feather: Feather,
    gauge: Gauge,
    globe: Globe,
    graduationCap: GraduationCap,
    layers: Layers,
    layout: Layout,
    layoutDashboard: LayoutDashboard,
    lightbulb: Lightbulb,
    mail: Mail,
    mapPin: MapPin,
    messageCircle: MessageCircle,
    monitor: Monitor,
    moon: Moon,
    moreHorizontal: MoreHorizontal,
    network: Network,
    palette: Palette,
    plug: Plug,
    puzzle: Puzzle,
    rocket: Rocket,
    search: Search,
    server: Server,
    settings: Settings,
    shieldCheck: ShieldCheck,
    shoppingCart: ShoppingCart,
    smartphone: Smartphone,
    sparkles: Sparkles,
    target: Target,
    trendingUp: TrendingUp,
    truck: Truck,
    users: Users,
    wrench: Wrench,
    zap: Zap,
    notebookPen: NotebookPen,
    github: FaGithub,
    linkedin: FaLinkedin,
}
